#! /bin/sh

# Do nothing if interrupted
trap '' INT TSTP

picom -f &

# Monitor Setup

bspc monitor "DP-2" -s "DP-4"
bspc monitor DP-2 -d I II III IV V VI
bspc monitor DP-4 -d VII VIII IX X

bspc config bottom_monocle_padding 3
bspc config border_width 6
bspc config right_padding 2
bspc config left_padding 2
bspc config window_gap 10

# Colors
bspc config presel_feedback_color "#141d2b"
# bspc config focused_border_color "#313f55"
# bspc config normal_border_color "#141d2b"
# bspc config presel_feedback_color "#141d2b"
# $HOME/.config/bspwm/colors/catppuccin
# $HOME/.config/bspwm/colors/one-dark
# $HOME/.config/bspwm/colors/gruvbox-dark
# $HOME/.config/bspwm/colors/nord
$HOME/.config/bspwm/colors/wizard

bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config single_monocle true
bspc config ignore_ewmh_focus true

### Rules

# Cleanup
bspc rule -r '*'


### Other stuff

# In order for resizing with super and mouse to work
bspc config pointer_modifier mod4
bspc config pointer_action1 move

# State rules
bspc rule -a "Zathura" state=tiled
bspc rule -a "KeePassXC" state=floating follow=on center=on
bspc rule -a "Discord" desktop='^8' state=tiled

##### autostart scripts
$HOME/.local/bin/bspwm/startup.sh &